server.port=${PORT:8080}
spring.application.name=email-writer-sb

# Gemini API Configuration
gemini.api.url=${GEMINI_URL}
gemini.api.key=${GEMINI_KEY}

# Logging
logging.level.root=INFO
logging.level.com.email=DEBUG
